version: "3.8"

name: pact_dashboard

services:
  web:
    image: docker.io/${DOCKERHUB_USERNAME}/pact_dashboard:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - pact_dashboard_network

networks:
  pact_dashboard_network:
    driver: bridge

